/**:
  ros__parameters:
    plugin_denylist:
      # common
      - actuator_control
      - ftp
      - hil
      - param
      - waypoint
      # setpoints (not used)
      - setpoint_accel
      - setpoint_attitude
      - setpoint_position
      - setpoint_raw
      - setpoint_trajectory
      - setpoint_velocity
      # extras
      - adsb
      - altitude
      - cam_imu_sync
      - camera
      - cellular_status
      - companion_process_status
      - debug_value
      - distance_sensor
      - esc_status
      - esc_telemetry
      - fake_gps
      - geofence
      - gimbal_control
      - gps_input
      - gps_rtk
      - guided_target
      - home_position
      - image_pub
      - landing_target
      - log_transfer
      - mag_calibration_status
      - manual_control
      - mocap_pose_estimate
      - mount_control
      - nav_controller_output
      - obstacle_distance
      - onboard_computer_status
      - open_drone_id
      - optical_flow
      - play_tune
      - px4flow
      - rallypoint
      - rangefinder
      - rc_io
      - tdr_radio
      - terrain
      - trajectory
      - tunnel
      - vfr_hud
      - vibration
      - vision_pose
      - vision_speed
      - wheel_odometry
      - wind_estimation
